server:
  port: 8763

eureka:
  instance:
    hostname: localhost
  server:
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.server.port}/eureka/

spring:
  application:
    name: ribbon